### ISSUE TITLE
How can I create a crash log on linux? Using nostalrius 7.7

### ISSUE THREAD

**Issue by goesraphael** [TwistedScorpio/Nostalrius#66]
Hello guys! My server crashed two times already, first time on oct 19 and another one on oct 20.

I have no idea of what happened, how I do not have a log file, I can't reproduce the crash.

I didn't had any ideia if there was a log to look into. So I decided to search everywhere, I found this logs on linux, can someone help me?

I need to know if these are the crash logs and, if it is, what do they mean and what should I do to fix it to do not crash anymore.

The folder and file that I found something in the exactly minute that the server crashed:
**/var/log/kern.log**

**Oct 19:**
`Oct 19 11:55:42 nostalgicot kernel: [ 3383.201399] tfs[1120]: segfault at 45 ip 0000000000000045 sp 00007f2a35052d48 error 14`

**Oct 20:**
```
Oct 20 23:49:42 nostalgicot kernel: [87852.127862] traps: tfs[12040] general protection ip:555bd1560ce4 sp:7f7618748980 error:0
Oct 20 23:49:42 nostalgicot kernel: [87852.127872]  in tfs[555bd1270000+499000]
```

If these are not the logs that can tell me what is wrong and how to fix it, could someone help me, teach me, or tell me where to learn how to generate logs of crashes that happens from now on, for the next time I be prepared?

**Comment by goesraphael** [comment]
I've runned gdb on my host, the server crashed, that is the log I received, any idea?

`#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff620942a in __GI_abort () at abort.c:89
#2  0x00007ffff7b8af67 in ?? () from /usr/lib/x86_64-linux-gnu/libmariadb.so.2
#3  0x00007ffff7b98755 in ?? () from /usr/lib/x86_64-linux-gnu/libmariadb.so.2
#4  0x00007ffff7ba0b11 in ?? () from /usr/lib/x86_64-linux-gnu/libmariadb.so.2
#5  0x00007ffff7ba0dad in ?? () from /usr/lib/x86_64-linux-gnu/libmariadb.so.2
#6  0x00007ffff7b9c149 in mysql_real_query () from /usr/lib/x86_64-linux-gnu/libmariadb.so.2
#7  0x00005555556d69fe in Database::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x00005555556db696 in DatabaseTasks::runTask(DatabaseTask const&) ()
#9  0x00005555556db4b5 in DatabaseTasks::threadMain() ()
#10 0x00005555556dde56 in void std::__invoke_impl<void, void (DatabaseTasks::* const&)(), DatabaseTasks*>(std::__invoke_memfun_deref, void (DatabaseTasks::* const&)(), DatabaseTasks*&&) ()
#11 0x00005555556ddde3 in std::result_of<void (DatabaseTasks::* const&(DatabaseTasks*&&))()>::type std::__invoke<void (DatabaseTasks::* const&)(), DatabaseTasks*>(void (DatabaseTasks::* const&)(), DatabaseTasks*&&) ()
#12 0x00005555556ddd94 in decltype (__invoke((*this)._M_pmf, (forward<DatabaseTasks*>)({parm#1}))) std::_Mem_fn_base<void (DatabaseTasks::*)(), true>::operator()<DatabaseTasks*>(DatabaseTasks*&&) const ()
#13 0x00005555556ddd5f in void std::_Bind_simple<std::_Mem_fn<void (DatabaseTasks::*)()> (DatabaseTasks*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) ()
#14 0x00005555556ddcad in std::_Bind_simple<std::_Mem_fn<void (DatabaseTasks::*)()> (DatabaseTasks*)>::operator()() ()
#15 0x00005555556ddc8c in std::thread::_State_impl<std::_Bind_simple<std::_Mem_fn<void (DatabaseTasks::*)()> (DatabaseTasks*)> >::_M_run()
    ()
#16 0x00007ffff6b48e6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007ffff6e184a4 in start_thread (arg=0x7fffeffff700) at pthread_create.c:456
#18 0x00007ffff62bdd0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97`

**Comment by goesraphael** [comment]
unknown: debugger aborting because missing DBUG_RETURN or DBUG_VOID_RETURN macro in function "?func"
